<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.14159"/>

  <property name="base_height" value="0.043" />
  <property name="base_radius" value="0.048" />
  <property name="link1_height" value="0.006" />
  <property name="link1_radius" value="0.048" />
  <property name="link2_offset" value="0.022" />
  <property name="link2_length" value="0.14605" />
  <property name="link3_length" value="0.187325" />
  <property name="link4_length" value="0.032" />
  <property name="gripper_offset" value="0.016" />
  
  <xacro:macro name="lynxmotion_al5d" params="prefix parent_link *origin">
    <!-- attach -->
    <joint name="arm_base_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent_link}"/>
      <child link="${prefix}base_link" />
    </joint>
    <!-- links -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${base_height}" radius="${link1_radius}"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${link1_height}" radius="${link1_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
           <cylinder length="${link1_height}" radius="${base_radius}"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_2">
      <visual>
        <origin xyz="${link2_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link2_length-0.02} 0.02 .02"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${link2_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link2_length-0.02} 0.02 .02"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_3">
      <visual>
        <origin xyz="${link3_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link3_length-0.02} 0.02 0.02"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${link3_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link3_length} 0.02 0.02"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_4">
      <visual>
        <origin xyz="${link4_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link4_length} 0.02 0.02"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${link4_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link4_length} 0.02 0.02"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}gripper">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 0.05"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.025" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 0.05"/>
        </geometry>
      </collision>
    </link>

    <!-- joints -->
    <joint name="${prefix}joint_1" type="revolute">
      <origin xyz="0 0 ${base_height + link1_height}" rpy="0 0 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link_1"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="3.67"/>
    </joint>
    <joint name="${prefix}joint_2" type="revolute">
      <origin xyz="0 0 ${link2_offset}" rpy="${M_PI/2} 0 0"/>
      <parent link="${prefix}link_1"/>
      <child link="${prefix}link_2"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="3.32"/>
    </joint>
    <joint name="${prefix}joint_3" type="revolute">
      <origin xyz="${link2_length} 0 0" rpy="0 0 0" />
      <parent link="${prefix}link_2"/>
      <child link="${prefix}link_3"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="3.67"/>
    </joint>
    <joint name="${prefix}joint_4" type="revolute">
      <origin xyz="${link3_length} 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_3"/>
      <child link="${prefix}link_4"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="6.98"/>
    </joint>
    <joint name="${prefix}gripper" type="fixed">
      <origin xyz="${link4_length + gripper_offset} 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_4"/>
      <child link="${prefix}gripper"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="6.98"/>
    </joint>
  </xacro:macro>
</robot>
