// Generated by gencpp from file moveit_msgs/GetKinematicSolverInfo.msg
// DO NOT EDIT!


#ifndef MOVEIT_MSGS_MESSAGE_GETKINEMATICSOLVERINFO_H
#define MOVEIT_MSGS_MESSAGE_GETKINEMATICSOLVERINFO_H

#include <ros/service_traits.h>


#include <moveit_msgs/GetKinematicSolverInfoRequest.h>
#include <moveit_msgs/GetKinematicSolverInfoResponse.h>


namespace moveit_msgs
{

struct GetKinematicSolverInfo
{

typedef GetKinematicSolverInfoRequest Request;
typedef GetKinematicSolverInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetKinematicSolverInfo
} // namespace moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_msgs::GetKinematicSolverInfo > {
  static const char* value()
  {
    return "9b591d98efeb66095c1b33a70221cab5";
  }

  static const char* value(const ::moveit_msgs::GetKinematicSolverInfo&) { return value(); }
};

template<>
struct DataType< ::moveit_msgs::GetKinematicSolverInfo > {
  static const char* value()
  {
    return "moveit_msgs/GetKinematicSolverInfo";
  }

  static const char* value(const ::moveit_msgs::GetKinematicSolverInfo&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_msgs::GetKinematicSolverInfoRequest> should match 
// service_traits::MD5Sum< ::moveit_msgs::GetKinematicSolverInfo > 
template<>
struct MD5Sum< ::moveit_msgs::GetKinematicSolverInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_msgs::GetKinematicSolverInfo >::value();
  }
  static const char* value(const ::moveit_msgs::GetKinematicSolverInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_msgs::GetKinematicSolverInfoRequest> should match 
// service_traits::DataType< ::moveit_msgs::GetKinematicSolverInfo > 
template<>
struct DataType< ::moveit_msgs::GetKinematicSolverInfoRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_msgs::GetKinematicSolverInfo >::value();
  }
  static const char* value(const ::moveit_msgs::GetKinematicSolverInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_msgs::GetKinematicSolverInfoResponse> should match 
// service_traits::MD5Sum< ::moveit_msgs::GetKinematicSolverInfo > 
template<>
struct MD5Sum< ::moveit_msgs::GetKinematicSolverInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_msgs::GetKinematicSolverInfo >::value();
  }
  static const char* value(const ::moveit_msgs::GetKinematicSolverInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_msgs::GetKinematicSolverInfoResponse> should match 
// service_traits::DataType< ::moveit_msgs::GetKinematicSolverInfo > 
template<>
struct DataType< ::moveit_msgs::GetKinematicSolverInfoResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_msgs::GetKinematicSolverInfo >::value();
  }
  static const char* value(const ::moveit_msgs::GetKinematicSolverInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_GETKINEMATICSOLVERINFO_H
